### ISSUE TITLE
Milestone 3 - Create a Sequence Diagram of Most Complicated Use Case

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#36]
Choose the most complicated of your use cases from Milestone 2 and create
a sequence diagram for it like page 365 of the text book. Embed the image of
the sequence diagram in this file. Make sure you show all three layers of the
MVC architecture in your sequence diagram

[Project Milestone 3 - 01.pdf](https://github.com/user-attachments/files/17036708/Project.Milestone.3.-.01.pdf)

**Comment by PaulTrevizo** [comment]
Hello @caLeb-centy. Here is my first draft of the sequence diagram for adding a review. Because there are two parts to adding a review (add the review text and selecting the number of stars) I added a color code to that to show the difference. 

Let me know your thoughts!
![Sequence Diagram](https://github.com/user-attachments/assets/504b7d85-ef31-412c-95bb-0ac0c1bd1928)

**Comment by caLeb-centy** [comment]
Could u put a dashed line that says “acknowledgement” after the view notifies the controller?  That way we show that the system  successfully recognizes the users request to write a review🙏

**Comment by PaulTrevizo** [comment]
@caLeb-centy what about this?
![Sequence Diagram Draft v2](https://github.com/user-attachments/assets/4bdd5bf2-0711-4d48-b773-d8d842509171)

**Comment by caLeb-centy** [comment]
This is good 🙏

**Comment by PaulTrevizo** [comment]
Thank you!

**Comment by PaulTrevizo** [comment]
Committing the diagram to Architecture.md
