### ISSUE TITLE
Milestone 3 - Update CHANGELOG.md (comment your submissions here)

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#37]

**Comment by Nicholas2501** [comment]
@dogfriendbookclub I uploaded my classes to the main branch. There are 3 new Classes that will need to be updated on the UML. There's the API Client, Creator and Genre class, I had to make these due to how they were structured in the movie database API. I also changed some gradle dependencies so now we have http client and Jackson dependency. Lastly, I removed some of the variables in the episode UML as I think it might be too much information to fit onto a view. Main ones I removed were cast and director in episode.

**Comment by PaulTrevizo** [comment]
Hi @dogfriendbookclub. 

I implemented Reviewable, Likeable, and MediaType interfaces per issue log item 31 (https://github.com/dogfriendbookclub/Application/issues/31). I was assisted by you.

I also created the sequence diagram of the "User Submits Reviews" use case, per issue log item 36 (https://github.com/dogfriendbookclub/Application/issues/36). I was assisted by Caleb.

**Comment by dogfriendbookclub** [comment]
i implemented the user class, made some edits to other classes as needed, updated the uml diagram and updated changelog
