### ISSUE TITLE
Develop a list of possible features for the application.

### ISSUE THREAD

**Issue by dogfriendbookclub** [dogfriendbookclub/Application#4]
[Project Milestone 1 - 01.pdf](https://github.com/user-attachments/files/16775838/Project.Milestone.1.-.01.pdf)

**Comment by Nicholas2501** [comment]
@caLeb-centy I was able to copy your changes and push the pull request through so the features.md should be updated on the main branch now.

**Comment by Chang-Vang** [comment]
Made tons of changes to features.md

Changes made - Grammar and Spacing changes on where needed and elaborated on descriptions.

Capitalized "TV" where needed.
Replaced "tv shows" with "TV shows."
Corrected "anytime" to "any time."
Changed "A users profile" to "A user's profile."
Capitalized "X" as a placeholder.
Corrected "a set of emoji's" to "a set of emojis."
Removed repeated "sad" emoji.
Fixed "teh" to "the."
Changed "combing" to "combining."
Removed unnecessary commas.
Adjusted formatting and grammar for clarity.

Otherwise everything else looks smooth!

**Comment by dogfriendbookclub** [comment]
thanks for creating that list and editing everything!! i'm going to close this out now
